sudo: true
dist: trusty

language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh  

script:
  - ./functional_tests/barcode_analysis-test.sh -p barcode_analysis -d functional_tests/test_data
  - ./.travis/unit-test.sh
